- src/Language.yml
- src/de/codingair/tradesystem/TradeSystem.java
- src/de/codingair/tradesystem/trade/commands/TradeSystemCMD.java
- src/de/codingair/tradesystem/trade/layout/LayoutManager.java
* changed the console output while loading/disabling
> [TS-06] Add a reload command

- src/de/codingair/tradesystem/trade/Trade.java
- src/de/codingair/tradesystem/trade/TradingGUI.java
* Fixed that bug, that you could cancel the trade with the SHOW_READY icon
> [TS-32] Kills the duplication bug

- src/Config.yml
- src/de/codingair/tradesystem/trade/Trade.java
- src/de/codingair/tradesystem/trade/TradeManager.java
- src/de/codingair/tradesystem/trade/TradingGUI.java
* Buffering TradeGUI
* Better Config
* MoneyReplacements are shown correctly (removed name, ...)
> [TS-046] Finish trade with just one commit

- src/Language.yml
- src/de/codingair/tradesystem/trade/commands/TradeCMD.java
- src/de/codingair/tradesystem/trade/listeners/TradeListener.java
Minecraft client bug: When a player lies in a bed and it opens a inventory, the InventoryClickEvents won't be fired
> [WS-074] Prevents from trading in a bed

- src/de/codingair/tradesystem/TradeSystem.java
- src/de/codingair/tradesystem/trade/Trade.java
- src/de/codingair/tradesystem/trade/TradingGUI.java
- src/de/codingair/tradesystem/utils/Profile.java
- src/de/codingair/tradesystem/utils/money/Adapter.java
- src/de/codingair/tradesystem/utils/money/AdapterType.java
- src/de/codingair/tradesystem/utils/money/adapters/Essentials.java
- src/de/codingair/tradesystem/utils/money/adapters/Vault.java
> [TS-091] 1.14 Update

- src/plugin.yml
* Updates plugin version to v1.1.0
> [TS-097] Fixed a bug with an AnvilGUI (Paying exp for nothing)

- src/de/codingair/tradesystem/trade/Trade.java
- src/de/codingair/tradesystem/trade/TradingGUI.java
- src/plugin.yml
* Changes plugin version to v1.1.3
> [TS-118] Fixes dupe glitch

- src/de/codingair/tradesystem/TradeSystem.java
- src/de/codingair/tradesystem/bstats/Metrics.java
- src/de/codingair/tradesystem/bstats/MetricsManager.java
- src/de/codingair/tradesystem/trade/TradeManager.java
- src/de/codingair/tradesystem/trade/commands/TradeCMD.java
- src/de/codingair/tradesystem/utils/blacklist/BlockedItem.java
- src/plugin.yml
* Changes plugin version to 1.1.5
* Fixes Player#hasPermission(null) query
> [TS-143] Adds plugin metrics

- src/de/codingair/tradesystem/TradeSystem.java
- src/de/codingair/tradesystem/trade/commands/TradeCMD.java
- src/de/codingair/tradesystem/trade/commands/TradeSystemCMD.java
- src/plugin.yml
* Fixes vanish protection
* Changes plugin version to 1.1.12
closes #176
> [TS-176] Supports Minecraft 1.16.1

- src/de/codingair/tradesystem/trade/TradingGUI.java
- src/de/codingair/tradesystem/trade/commands/TradeSystemCMD.java
> [TS-174] Fixes money icon bug

- src/de/codingair/tradesystem/trade/commands/TradeCMD.java
- src/plugin.yml
* Changes plugin version to v1.1.13
closes #175
> [TS-175] Nothing to improve here.

- src/main/java/de/codingair/tradesystem/trade/listeners/TradeListener.java
> [TS-193] Fixes active trade requests after changing worlds

- src/main/java/de/codingair/tradesystem/trade/TradeManager.java
> [TS-192] Fixes dupe glitch with already opened inventories

- src/main/java/de/codingair/tradesystem/trade/Trade.java
- src/main/java/de/codingair/tradesystem/trade/TradingGUI.java
> [TS-196] Fixes dupe glitch when a player swap an item with his offhand

- src/main/java/de/codingair/tradesystem/trade/commands/TradeCMD.java
- src/main/java/de/codingair/tradesystem/trade/listeners/TradeListener.java
> [TS-193] Fixes active trade requests after world changes

- pom.xml
> [TS-186] Fixes type specification on TacoSpigot 1.8.8

- .github/workflows/build-deploy.yml
- pom.xml
- src/main/java/de/codingair/tradesystem/TradeSystem.java
- src/main/java/de/codingair/tradesystem/extras/placeholderapi/PAPI.java
- src/main/java/de/codingair/tradesystem/trade/Trade.java
- src/main/java/de/codingair/tradesystem/tradelog/TradeLog.java
- src/main/java/de/codingair/tradesystem/tradelog/TradeLogOptions.java
- src/main/java/de/codingair/tradesystem/tradelog/TradeLogService.java
- src/main/java/de/codingair/tradesystem/tradelog/repository/adapters/MysqlTradeLogRepository.java
- src/main/java/de/codingair/tradesystem/utils/database/DatabaseInitializer.java
- src/main/java/de/codingair/tradesystem/utils/database/DatabaseUtil.java
- src/main/java/de/codingair/tradesystem/utils/database/migrations/mysql/MySQLConnection.java
- src/main/java/de/codingair/tradesystem/utils/database/migrations/mysql/MysqlMigrations.java
- src/main/java/de/codingair/tradesystem/utils/database/migrations/sqlite/SqLiteMigrations.java
- src/main/java/de/codingair/tradesystem/utils/updates/UpdateChecker.java
- src/main/resources/Config.yml
* Fix trade log
* Remove logger when tradelog is disabled
* Add "_Hotfix" tag for updates (avoid sending 'new update available' message)
* Fix numeric entities in update titles
* Add BETA warning to the tradelog subsection in the config
Fixes #220
> Fix own placeholder when PlaceholderAPI is missing

- src/main/java/de/codingair/tradesystem/trade/TradeManager.java
- src/main/java/de/codingair/tradesystem/trade/commands/TradeCMD.java
- src/main/java/de/codingair/tradesystem/utils/BackwardSupport.java
- src/main/resources/Config.yml
* Change 'Request_Cooldown_In_Sek' into 'Trade_Request_Expiration_Time' (values are moved automatically)
> Fix correct trade request expiration time

- pom.xml
> Fix not synchronizing items after changing their amount

- .github/workflows/build-deploy.yml
- pom.xml
- src/main/java/de/codingair/tradesystem/TradeSystem.java
- src/main/java/de/codingair/tradesystem/extras/placeholderapi/PAPI.java
- src/main/java/de/codingair/tradesystem/trade/Trade.java
- src/main/java/de/codingair/tradesystem/trade/TradeManager.java
- src/main/java/de/codingair/tradesystem/trade/commands/TradeCMD.java
- src/main/java/de/codingair/tradesystem/tradelog/TradeLog.java
- src/main/java/de/codingair/tradesystem/tradelog/TradeLogOptions.java
- src/main/java/de/codingair/tradesystem/tradelog/TradeLogService.java
- src/main/java/de/codingair/tradesystem/tradelog/repository/adapters/MysqlTradeLogRepository.java
- src/main/java/de/codingair/tradesystem/utils/BackwardSupport.java
- src/main/java/de/codingair/tradesystem/utils/database/DatabaseInitializer.java
- src/main/java/de/codingair/tradesystem/utils/database/DatabaseUtil.java
- src/main/java/de/codingair/tradesystem/utils/database/migrations/mysql/MySQLConnection.java
- src/main/java/de/codingair/tradesystem/utils/database/migrations/mysql/MysqlMigrations.java
- src/main/java/de/codingair/tradesystem/utils/database/migrations/sqlite/SqLiteMigrations.java
- src/main/java/de/codingair/tradesystem/utils/updates/UpdateChecker.java
- src/main/resources/Config.yml
* Fix own placeholder when PlaceholderAPI is missing
* Fix correct trade request expiration time
* Fix not synchronizing items after changing their amount
> A few bugfixes

- src/main/java/de/codingair/tradesystem/trade/Trade.java
- src/main/java/de/codingair/tradesystem/trade/TradeManager.java
> Fix running countdowns without delay

- src/main/resources/languages/CZE.yml
New translation to Czech language.
> Czech translation

- src/main/java/de/codingair/tradesystem/trade/commands/TradeCMD.java
- src/main/java/de/codingair/tradesystem/trade/listeners/TradeListener.java
> [TS-251] Fix bypassed trade rules

- TradeSystem-Spigot/src/main/java/de/codingair/tradesystem/spigot/trade/ProxyTrade.java
- TradeSystem-Spigot/src/main/java/de/codingair/tradesystem/spigot/trade/managers/InvitationManager.java
- TradeSystem-Spigot/src/main/java/de/codingair/tradesystem/spigot/trade/managers/RequestManager.java
- TradeSystem-Spigot/src/main/java/de/codingair/tradesystem/spigot/transfer/ProxyDataManager.java
Closes: https://github.com/CodingAir/TradeSystem/issues/388
Explanation of the problem can be found in the same issue.
> Fixed problems with name completion

- TradeSystem-Spigot/src/main/resources/plugin.yml
Now consistent with spigot.util.Permission
> Fix permission error in plugin.yml

- TradeSystem-Spigot/src/main/java/de/codingair/tradesystem/spigot/TradeSystem.java
- TradeSystem-Spigot/src/main/java/de/codingair/tradesystem/spigot/extras/bstats/MetricsManager.java
- TradeSystem-Spigot/src/main/java/de/codingair/tradesystem/spigot/utils/BackwardSupport.java
- pom.xml
> upgrade CodingAPI

- TradeSystem-Spigot/src/main/java/de/codingair/tradesystem/spigot/commands/TradeCMD.java
- TradeSystem-Spigot/src/main/java/de/codingair/tradesystem/spigot/commands/TradeSystemCMD.java
- TradeSystem-Spigot/src/main/java/de/codingair/tradesystem/spigot/extras/external/worldguard/WorldGuardDependency.java
- TradeSystem-Spigot/src/main/java/de/codingair/tradesystem/spigot/extras/tradelog/commands/TradeLogCMD.java
- TradeSystem-Spigot/src/main/java/de/codingair/tradesystem/spigot/trade/Trade.java
- TradeSystem-Spigot/src/main/java/de/codingair/tradesystem/spigot/trade/TradeHandler.java
- TradeSystem-Spigot/src/main/java/de/codingair/tradesystem/spigot/trade/gui/TradeGUIListener.java
- TradeSystem-Spigot/src/main/java/de/codingair/tradesystem/spigot/trade/gui/editor/LayoutPage.java
- TradeSystem-Spigot/src/main/java/de/codingair/tradesystem/spigot/trade/gui/layout/types/impl/economy/EconomyIcon.java
- TradeSystem-Spigot/src/main/java/de/codingair/tradesystem/spigot/trade/managers/InvitationManager.java
- TradeSystem-Spigot/src/main/java/de/codingair/tradesystem/spigot/trade/managers/RuleManager.java
- TradeSystem-Spigot/src/main/java/de/codingair/tradesystem/spigot/transfer/handlers/InviteResponsePacketHandler.java
- TradeSystem-Spigot/src/main/java/de/codingair/tradesystem/spigot/transfer/handlers/TradeInvitePacketHandler.java
- TradeSystem-Spigot/src/main/java/de/codingair/tradesystem/spigot/utils/Lang.java
> [TS-449] Hide empty messages

- TradeSystem-Spigot/pom.xml
- TradeSystem-Spigot/src/main/java/de/codingair/tradesystem/spigot/trade/TradeHandler.java
- TradeSystem-Spigot/src/main/java/de/codingair/tradesystem/spigot/trade/gui/layout/types/InputIcon.java
- TradeSystem-Spigot/src/main/java/de/codingair/tradesystem/spigot/trade/gui/layout/types/gui/FloodgateGUIIcon.java
- TradeSystem-Spigot/src/main/java/de/codingair/tradesystem/spigot/utils/updates/UpdateNotifier.java
- TradeSystem-Spigot/src/main/resources/Config.yml
- TradeSystem-Spigot/src/main/resources/languages/ENG.yml
- TradeSystem-Spigot/src/main/resources/plugin.yml
Fix https://github.com/erikzimmermann/TradeSystem/issues/492
Fix https://github.com/erikzimmermann/TradeSystem/issues/496
Maybe a fix for https://github.com/erikzimmermann/TradeSystem/issues/467 since it also could be related to bedrock
This allows bedrock players to have an alternative input that will allow them to enter the sum to trade, since the sign and anvil are a bit broken on bedrock
> Better bedrock input

- TradeSystem-Spigot/src/main/java/de/codingair/tradesystem/spigot/trade/listeners/TradeListener.java
- TradeSystem-Spigot/src/main/java/de/codingair/tradesystem/spigot/trade/managers/InvitationManager.java
- TradeSystem-Spigot/src/main/java/de/codingair/tradesystem/spigot/trade/managers/RequestManager.java
- TradeSystem-Spigot/src/main/java/de/codingair/tradesystem/spigot/trade/managers/RuleManager.java
> Replacers fix
